{
 "title": "Libvirt Dashboard",
 "description": "\nhttps://github.com/ycy1766/prometheus-libvirt-exporter",
 "tags": [ "libvirt" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(go_info{instance=~\".*:9177\"}, job)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(libvirt_domain_info_vstate{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "os",
    "query": {
     "query": "label_values(libvirt_domain_block_meta{domain=~\"$vm_name\", source_file!~\".*virtio.*\"}, source_file)"
    }
   },
   {
    "name": "uuid",
    "label": "UUID",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{instance=~\"$host\"}, uuid)"
    }
   },
   {
    "name": "instance_name",
    "label": "Instance",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{instance=~\"$host\", uuid=~\"$uuid\"}, instance_name)"
    }
   },
   {
    "name": "vm_name",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{job=~\"$job\", instance=~\"$host\",  instance_name=~\"$instance_name\"}, domain)"
    }
   },
   {
    "name": "domain",
    "query": {
     "query": "label_values(libvirt_domain_info_meta, domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OPS COUNT VM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(libvirt_domain_info_vstate{domain=~\"$domain\"})"
    }
   ]
  },
  { "title": "$instance_name -- [ INFO_VM ]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Status VM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "libvirt_domain_info_vstate{domain=~\"$vm_name\"}"
    }
   ]
  },
  {
   "title": "Count Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_block_stats_capacity_bytes{domain=~\"$vm_name\", target_device!~\".*hd.*\"})",
     "legendFormat": "{{target_device}}"
    }
   ]
  },
  {
   "title": "Count CPU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_virtual_cpus{domain=~\"$vm_name\"})"
    }
   ]
  },
  {
   "title": "Count RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_maximum_memory_bytes{domain=~\"$vm_name\"})"
    }
   ]
  },
  {
   "title": "Image",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 5 },
   "options": { "content": "$os" },
   "targets": [
    {}
   ]
  },
  {
   "title": "libvirt_domain_info_memory_usage_bytes",
   "type": "graph",
   "description": "Memory usage of the domain, in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(libvirt_domain_info_memory_usage_bytes{domain=~\"$vm_name\"})",
     "legendFormat": "memory_usage_bytes"
    }
   ]
  },
  {
   "title": "libvirt_domain_info_cpu_time_seconds_total",
   "type": "graph",
   "description": "Amount of CPU time used by the domain, in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_info_cpu_time_seconds_total{domain=~\"$vm_name\"}[5m]))",
     "legendFormat": "cpu_usage"
    }
   ]
  },
  {
   "title": "$instance_name\t-- [ Disk I/O ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "Block Read/Write Bytes",
   "type": "graph",
   "description": "Read - Number of bytes read from a block device, in bytes\n\nWrite - Number of bytes written to a block device, in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_bytes_total{domain=~\"$vm_name\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_bytes_total{domain=~\"$vm_name\"}[5m]))",
     "legendFormat": "Write "
    }
   ]
  },
  {
   "title": "Block Read/Write Request",
   "type": "graph",
   "description": "Read Request - Number of read requests from a block device\n\nWrite  Requests - Number of write requests to a block device",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_block_stats_read_requests_total{domain=~\"$vm_name\"}[5m]))",
     "legendFormat": "Read Requests"
    },
    {
     "expr": "sum(irate(libvirt_domain_block_stats_write_requests_total{domain=~\"$vm_name\"}[5m]))",
     "legendFormat": "Write  Requests"
    }
   ]
  },
  {
   "title": "$instance_name\t -- [ NETWORK INTERFAACE ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "interface_stats_byte",
   "type": "graph",
   "description": "RX - Number of bytes received on a network interface, in bytes\n\nTX - Number of bytes transmitted on a network interface, in bytes.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_bytes_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX "
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_bytes_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "interface_stats_package",
   "type": "graph",
   "description": "RX - Number of packets received on a network interface\n\nTX - Number of packets transmitted on a network interface",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_packets_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Package"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_packets_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Package"
    }
   ]
  },
  {
   "title": "Interface Error/Drop",
   "type": "graph",
   "description": "RX Drop - Number of packet receive drops on a network interface.\n\nTX Drop - Number of packet transmit drops on a network interface\n\nRX Error - Number of packet receive errors on a network interface.\n\nTX Error - Number of packet transmit errors on a network interface",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_drops_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_drops_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Drop"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_receive_errors_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "RX Error"
    },
    {
     "expr": "sum(irate(libvirt_domain_interface_stats_transmit_errors_total{domain=~\"$vm_name\"} [5m]))",
     "legendFormat": "TX Error"
    }
   ]
  }
 ]
}