{
 "title": "OpenStack Dashboard Monitor",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(openstack_nova_up, job)"
    }
   },
   { "name": "HeSoRAM", "label": "Hệ số cấp quá RAM node compute", "query": "170/100" },
   { "name": "HeSoCPU", "label": "Hệ số cấp quá CPU node compute", "query": "800/100" },
   { "name": "HeSoHypervisorCPU", "label": "He So Hypervisor CPU", "query": "10/100" },
   { "name": "HeSoHypervisorRAM", "label": "He So Hypervisor RAM", "query": "10/100" },
   { "name": "HeSoUtilization", "label": "He So Khai Thac RAM & CPU", "query": "80/100" },
   { "name": "HeSoHTCPU", "label": "He So Hyper-Thread CPU", "query": "30/100" }
  ]
 },
 "panels": [
  {
   "title": "Dung lượng Volume sử dụng thực tế",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Volume Group Total",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_total_gb{job=~\"$job\"}",
     "legendFormat": "{{volume_backend_name}}"
    }
   ]
  },
  {
   "title": "Volume Group Usage",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_total_gb{job=~\"$job\"} - openstack_cinder_pool_capacity_free_gb{job=~\"$job\"}",
     "legendFormat": "{{volume_backend_name}}"
    }
   ]
  },
  {
   "title": "Volume Group Free",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_pool_capacity_free_gb{job=~\"$job\"}",
     "legendFormat": "{{volume_backend_name}}"
    }
   ]
  },
  {
   "title": "Dung lượng Volume sử dụng trên lý thuyết [ Đã cấp cho VM ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Tổng dung lượng các volume đã gán cho VM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_volume_gb{job=~\"$job\"})"
    }
   ]
  },
  { "title": "Hypervisor Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "VCPUs Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_vcpus_available{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "VCPUs Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_vcpus_used{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_memory_available_bytes{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_memory_used_bytes{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Tổng năng lực cung cấp dịch vụ cho VM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "Tổng năng lực CCDV vCPU (cores)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(openstack_nova_vcpus_available{job=~\"$job\"}*(1+${HeSoHTCPU})/(1+${HeSoHypervisorCPU}))*${HeSoCPU}*${HeSoUtilization}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Tổng năng lực CCDV RAM(GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(openstack_nova_memory_available_bytes{job=~\"$job\"}/(1+${HeSoHypervisorRAM}))*${HeSoRAM}*${HeSoUtilization}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Nova Running VM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_running_vms{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Nova VM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_total_vms{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cinder agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(count(openstack_cinder_agent_state{adminState=\"enabled\",job=~\"$job\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\",job=~\"$job\"}))"
    }
   ]
  },
  {
   "title": "Neutron security groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_security_groups{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Glance Images",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_glance_images{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Neutron Networks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_neutron_networks{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Identity Projects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_projects{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Identity Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_identity_users{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Cinder Volumes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_cinder_volumes{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Nova flavors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openstack_nova_flavors{job=~\"$job\"}",
     "legendFormat": "images"
    }
   ]
  },
  {
   "title": "Cinder agent up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_cinder_agent_state{adminState=\"enabled\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Neutron agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Nova agents up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Nova agents down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openstack_nova_agent_state{adminState=\"enabled\",job=~\"$job\"})-sum(openstack_nova_agent_state{adminState=\"enabled\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Nova agent status",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{adminState=\"enabled\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cinder agent status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "openstack_cinder_agent_state{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "openstack_neutron_agent_state{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Cinder Volume GB",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "openstack_cinder_volume_gb{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Nova Server Local GB",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "openstack_nova_server_local_gb{job=~\"$job\"}"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Storage available",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "openstack_nova_local_storage_available_bytes{job=~\"$job\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_running_vms{job=~\"$job\"})",
     "legendFormat": "running vms"
    },
    {
     "expr": "sum(openstack_nova_total_vms{job=~\"$job\"})",
     "legendFormat": "total vms"
    }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(openstack_neutron_floating_ips) ",
     "legendFormat": "floating ips"
    },
    {
     "expr": "avg(openstack_neutron_networks)",
     "legendFormat": "networks"
    },
    {
     "expr": "avg(openstack_neutron_security_groups)",
     "legendFormat": "security groups"
    },
    { "expr": "avg(openstack_neutron_subnets)", "legendFormat": "subnets" }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_vcpus_used{job=~\"$job\"})",
     "legendFormat": "used vcpu cores"
    },
    {
     "expr": "sum(openstack_nova_vcpus{job=~\"$job\"})",
     "legendFormat": "total vcpu cores"
    }
   ]
  },
  {
   "title": "Overall memory usage (TiB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes", "label": "Memory in TiB" }
   ],
   "targets": [
    {
     "expr": "sum(openstack_nova_memory_used_bytes{job=~\"$job\"})",
     "legendFormat": "memory in use"
    },
    {
     "expr": "sum(openstack_nova_memory_available_bytes{job=~\"$job\"}) / 1024 / 1024 / 1024 / 1024",
     "legendFormat": "memory available"
    }
   ]
  },
  {
   "title": "Cinder volumes/snapshots",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(openstack_cinder_volumes{job=~\"$job\"})",
     "legendFormat": "volumes"
    },
    {
     "expr": "avg(openstack_cinder_snapshots{job=~\"$job\"})",
     "legendFormat": "snapshots"
    }
   ]
  }
 ]
}