{
 "title": "SNMP  Switch Stats",
 "description": "For snmp_exporter IF-MIB",
 "tags": [
  "Prometheus",
  "snmp_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus{job=\"$Job\"}, instance)"
    }
   },
   {
    "name": "ifName",
    "query": {
     "query": "query_result(ifOperStatus{instance=\"$instance\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Out / In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 11 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"$Job\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 11 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"$Job\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{job=\"$Job\"} * 10",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table-old",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  { "title": "Interface Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "table-old",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "ifType_info{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Admin Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 39 },
   "format": "timeticks",
   "valueName": "current",
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Connector Present",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifConnectorPresent{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Promiscuous Mode",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifPromiscuousMode{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 39 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifName=\"$ifName\"}*1000000 or ifSpeed{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  }
 ]
}